swagger: "2.0"
info:
  title: Contact Manager API
  version: 1.0.0
host: cop4331group10.xyz
basePath: /LAMPAPI
schemes:
  - http
paths:
  /SignUp.php:
    post:
      summary: up a user
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - name: firstName
          in: formData
          type: string
          required: true
        - name: lastName
          in: formData
          type: string
          required: true
        - name: login
          in: formData
          type: string
          required: true
        - name: password
          in: formData
          type: string
          required: true
      responses:
        200:
          description: User signed up successfully
        400:
          description: Invalid request body
  /Login.php:
    post:
      summary: Login to the system
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - name: Login
          in: formData
          description: The user's username
          required: true
          type: string
        - name: Password
          in: formData
          description: The user's password
          required: true
          type: string
      responses:
        '200':
          description: Login successful
        '401':
          description: Invalid username or password
  /AddContact.php:
      post:
        summary: Adds contact to User's contacts
        consumes:
          - application/x-www-form-urlencoded
        produces:
          - application/json
        parameters:
          - name: newFirstName
            in: formData
            description: The user's first name
            required: true
            type: string
          - name: newLastName
            in: formData
            description: The user's last name
            required: true
            type: string
          - name: phoneNumber 
            in: formData
            description: The user's phone number
            required: true
            type: string
          - name: emailAddress 
            in: formData
            description: The user's email address
            required: true
            type: string
          - name: id 
            in: formData
            description: The user's ID 
            required: true
            type: integer 
        responses:
          '200':
            description: OK
          '401':
            description: URL not found
  /DeleteContact.php:
    post:
      summary: Login to the system
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - name: firstName
          in: formData
          description: The contact's first name
          required: true
          type: string
        - name: lastName
          in: formData
          description: The contact's last name
          required: true
          type: string
        - name: userId
          in: formData
          description: The contact's userId
          required: true
          type: integer
      responses:
        '200':
          description: Login successful
        '401':
          description: URL not found
  /SearchContacts.php:
    post:
      summary: Searches for contacts
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - name: firstName
          in: formData
          description: The contact's first name
          required: true
          type: string
        - name: lastName
          in: formData
          description: The contact's last name
          required: true
          type: string
        - name: userID
          in: formData
          description: The contact's userId
          required: true
          type: string
      responses:
        '200':
          description: OK
        '401':
          description: URL not found
  /SearchUsers.php:
    post:
      summary: Searches for users in the database
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - name: login
          in: formData
          description: The user's login
          required: true
          type: string
      responses:
        '200':
          description: OK
        '401':
          description: Username already taken
  /UpdateContact.php:
    post:
      summary: Updates selected contact 
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - name: newFirst
          in: formData
          description: Contact's updated first name
          required: true
          type: string
        - name: newLast
          in: formData
          description: Contact's updated last name
          required: true
          type: string
        - name: phoneNumber
          in: formData
          description: Contact's phone number
          required: true
          type: string
        - name: emailAddress
          in: formData
          description: Contact's email address
          required: true
          type: string
        - name: id
          in: formData
          description: Contact's user ID
          required: true
          type: integer
      responses:
        '200':
          description: OK
        '401':
          description: URL not found